version: "3.9"

services:
  postgres:
    image: postgres:alpine
    container_name: sub_tracker_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sub_tracker}
      POSTGRES_USER: ${POSTGRES_USER:-sub_tracker_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sub_tracker_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sub_tracker_network

volumes:
  postgres_data:
    driver: local

networks:
  sub_tracker_network:
    driver: bridge
