spring:
  application:
    name: sub_tracker
  datasource:
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    verify:
      host: ${VERIFY_EMAIL_HOST}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    database-platform: com.sangtandoan.sub_tracker.configs.CustomPostgreSQLDialect
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

token:
  jwt:
    token-duration: 86400
    secret-key: ${JWT_SECRET}
