spring:
  application:
    name: sub_tracker
  datasource:
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

token:
  jwt:
    token-duration: 86400
    secret-key: ${JWT_SECRET}
