spring:
  application:
    name: sub_tracker
  datasource:
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jackson:
    property-naming-strategy: SNAKE_CASE

token:
  jwt:
    token-duration: 86400
    secret-key: ${JWT_SECRET}
